### ISSUE TITLE
where is the data under the directory train_softmax

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [WuJie1010/Temporally-language-grounding#1]
@WuJie1010 Thanks for the nice sharing!
Could you please tell me where is the data under the directory train_softmax_dir?

**Comment by WuJie1010** [comment]
please download in https://drive.google.com/open?id=1biKPDmb7hbzowKLMIRSTLE0w_tWbGPAe, and put in './Dataset/Charades/train_softmax/'
