### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by yufansong** [WuJie1010/Temporally-language-grounding#3]
Can you release the code about preprocessing the visual / sentence feature?
I want to know about how you get the visual feature (ResNet or others?) and what is the exact meaning of the sentence feature files.

**Comment by WuJie1010** [comment]
I extract the same feature as "Temporal Activity Localization via Language Query", please refer to their paper and their GitHub code~ 
visual feature:c3d~ 
sentence feature: skip-thought~
