### ISSUE TITLE
Data processing confusion

### ISSUE THREAD

**Issue by wuyou111** [WuJie1010/Temporally-language-grounding#9]
hi WuJie,Sorry to bother you. I was reading your code to reproduce the A2C model and I was wondering how you dealt with the dataset. How to get ref_info folder and charades_rl_train_feature.pkl. Maybe my knowledge level is not enough, I hope to get your advice, thank you very much!

**Comment by wuyou111** [comment]
ref_info/charades_sta_test_semantic_sentence_VP_sub_obj.pkl-------I tried to deserialize this file into a variable, I can roughly read the fields, but I don't know how to get it

**Comment by riariam** [comment]
> ref_info/charades_sta_test_semantic_sentence_VP_sub_obj.pkl-------I tried to deserialize this file into a variable, I can roughly read the fields, but I don't know how to get it

Hi,have you solved this problem?

**Comment by wuyou111** [comment]
> 

This is a nested dictionary with some fields that you can tell by the key value. A personal suggestion: some fields may not be used, and most of the fields can be extracted from the charades dataset, which is some dictionary operation

**Comment by wuyou111** [comment]
> > ref_info/charades_sta_test_semantic_sentence_VP_sub_obj.pkl-------I tried to deserialize this file into a variable, I can roughly read the fields, but I don't know how to get it
> 
> Hi,have you solved this problem?

This is a nested dictionary with some fields that you can tell by the key value. A personal suggestion: some fields may not be used, and most of the fields can be extracted from the charades dataset, which is some dictionary operation
